import { test, expect } from "@playwright/test";

test("assistant moves, resizes, remembers geometry and preserves its draft", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("link", { name: /Shop/ }).first().click();
  const launcher = page.getByRole("button", { name: "Agent", exact: true });
  await launcher.click();
  const chat = page.getByRole("complementary", { name: "Project conversation" });
  const input = chat.getByRole("textbox", { name: "Message the coding agent" });
  await input.fill("Explain this concept");
  const before = (await chat.boundingBox())!;
  const heading = (await chat.locator(".chat-heading").boundingBox())!;
  await page.mouse.move(heading.x + 90, heading.y + 18);
  await page.mouse.down();
  await page.mouse.move(heading.x - 150, heading.y + 70, { steps: 8 });
  await page.mouse.up();
  const moved = (await chat.boundingBox())!;
  expect(moved.x).toBeLessThan(before.x - 150);
  await expect(input).toHaveValue("Explain this concept");
  const grip = (await page.getByTestId("assistant-resize-nw").boundingBox())!;
  await page.mouse.move(grip.x + 7, grip.y + 7);
  await page.mouse.down();
  await page.mouse.move(grip.x - 63, grip.y - 33, { steps: 8 });
  const during = (await chat.boundingBox())!;
  await page.mouse.up();
  const resized = (await chat.boundingBox())!;
  expect(resized.width).toBeGreaterThan(moved.width + 50);
  expect(resized.x).toBeCloseTo(during.x, 0);
  expect(resized.y).toBeCloseTo(during.y, 0);
  expect(resized.x + resized.width).toBeCloseTo(moved.x + moved.width, 0);
  await page.keyboard.press("Control+Backslash");
  await expect(chat).toBeHidden();
  await launcher.focus();
  await page.keyboard.press("Enter");
  await expect(input).toHaveValue("Explain this concept");
  await page.screenshot({ path: "test-results/assistant-desktop.png" });
  await page.reload();
  await launcher.click();
  const restored = (await chat.boundingBox())!;
  expect(restored.width).toBeCloseTo(resized.width, 0);
  expect(restored.x).toBeCloseTo(resized.x, 0);
  const button = (await launcher.boundingBox())!;
  await page.mouse.move(button.x + 22, button.y + 22);
  await page.mouse.down();
  await page.mouse.move(30, 160, { steps: 10 });
  await page.mouse.up();
  await expect(chat).toBeVisible();
  expect((await launcher.boundingBox())!.x).toBe(12);
  await page.setViewportSize({ width: 390, height: 844 });
  const narrow = (await chat.boundingBox())!;
  expect(narrow.x).toBeGreaterThanOrEqual(0);
  expect(narrow.x + narrow.width).toBeLessThanOrEqual(390);
  expect(narrow.y + narrow.height).toBeLessThanOrEqual(844);
  await expect(input).toBeVisible();
  await chat.getByRole("button", { name: "Minimize Chat", exact: true }).click();
  await launcher.click();
  await expect(chat).toBeVisible();
  await page.screenshot({ path: "test-results/assistant-mobile.png" });
});


test("launcher docks into the toolbar and can be dragged out again", async ({ page }) => {
  await page.goto("/p/shop");
  const launcher = page.getByRole("button", { name: "Agent", exact: true });
  const toolbar = page.locator(".toolbar");
  const start = (await launcher.boundingBox())!;
  const target = (await toolbar.boundingBox())!;
  await page.mouse.move(start.x + 20, start.y + 20);
  await page.mouse.down();
  await page.mouse.move(target.x + target.width - 25, target.y + 20, { steps: 12 });
  await page.mouse.up();
  await expect(toolbar.getByRole("button", { name: "Agent", exact: true })).toBeVisible();
  await expect(page.locator(".chat-pane")).toBeHidden();
  await launcher.click();
  const input = page.getByRole("textbox", { name: "Message the coding agent" });
  await input.fill("Keep my draft");
  await page.getByRole("button", { name: "Float launcher", exact: true }).click();
  await expect(toolbar.getByRole("button", { name: "Agent", exact: true })).toHaveCount(0);
  await expect(input).toHaveValue("Keep my draft");
  await page.getByRole("button", { name: "Dock launcher in toolbar", exact: true }).click();
  await page.reload();
  await expect(toolbar.getByRole("button", { name: "Agent", exact: true })).toBeVisible();
  const dock = (await launcher.boundingBox())!;
  await page.mouse.move(dock.x + 15, dock.y + 15);
  await page.mouse.down();
  await page.mouse.move(dock.x - 100, dock.y + 180, { steps: 12 });
  await page.mouse.up();
  await expect(toolbar.getByRole("button", { name: "Agent", exact: true })).toHaveCount(0);
  await launcher.click();
  await expect(page.locator(".chat-pane")).toBeVisible();
  await page.getByRole("button", { name: "Dock launcher in toolbar", exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(launcher).toBeVisible();
  await expect(launcher).not.toHaveClass(/assistant-docked/);
  await page.setViewportSize({ width: 1280, height: 900 });
  await expect(toolbar.getByRole("button", { name: "Agent", exact: true })).toBeVisible();
});

test("floating launcher clears panel edges and context tooltips paint above chat", async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.goto("/p/shop");
  await page.getByRole("button", { name: "Concept · entity Order", exact: true }).click();
  const launcher = page.getByRole("button", { name: "Agent", exact: true });
  await launcher.click();
  const chat = page.locator(".chat-pane");
  const heading = chat.locator(".chat-heading");
  const assertClear = async () => {
    const a = (await launcher.boundingBox())!;
    const p = (await chat.boundingBox())!;
    expect(a.x + a.width <= p.x || a.x >= p.x + p.width || a.y + a.height <= p.y || a.y >= p.y + p.height).toBe(true);
    expect(a.x).toBeGreaterThanOrEqual(0);
    expect(a.x + a.width).toBeLessThanOrEqual(page.viewportSize()!.width);
    expect(a.y + a.height).toBeLessThanOrEqual(page.viewportSize()!.height);
  };
  for (const x of [1270, 10]) {
    const h = (await heading.boundingBox())!;
    await page.mouse.move(h.x + 80, h.y + 20);
    await page.mouse.down();
    await page.mouse.move(x, h.y + 20, { steps: 10 });
    await page.mouse.up();
    await assertClear();
  }
  await page.setViewportSize({ width: 800, height: 900 });
  const grip = (await page.getByTestId("assistant-resize-se").boundingBox())!;
  await page.mouse.move(grip.x + 9, grip.y + 9);
  await page.mouse.down();
  await page.mouse.move(788, 860, { steps: 10 });
  await page.mouse.up();
  await assertClear();
  await chat.locator(".chat-attachment .type-icon").hover();
  const tooltip = page.getByRole("tooltip");
  await expect(tooltip).toBeVisible();
  expect(await tooltip.evaluate(element => {
    const r = element.getBoundingClientRect();
    return element.contains(document.elementFromPoint(r.x + r.width / 2, r.y + r.height / 2));
  })).toBe(true);
});
