import { openAgentConversation, prepareAgent } from "./fixtures/agent-ui";
import { test, expect } from "@playwright/test";

test("canvas card moves independently, keeps its task identity and preserves conversation drafts", async ({ page }) => {
  await page.goto("/p/shop");
  const card = await prepareAgent(page);
  const before = (await card.boundingBox())!;
  await page.mouse.move(before.x + 40, before.y + 20);
  await page.mouse.down();
  await page.mouse.move(before.x + 140, before.y + 50, { steps: 8 });
  await page.mouse.up();
  const moved = (await card.boundingBox())!;
  expect(moved.x - before.x).toBeCloseTo(100, 0);
  expect(moved.y - before.y).toBeCloseTo(30, 0);
  await expect(page.locator("#chat-pane")).toBeHidden();
  await page.mouse.move(moved.x + 60, moved.y + 30);
  expect((await card.boundingBox())!.x).toBeCloseTo(moved.x, 0);
  await card.click();
  await openAgentConversation(page);
  const pane = page.locator("#chat-pane"), input = pane.getByLabel("Message the agent");
  await input.fill("Preserve this draft");
  await pane.getByRole("button", { name: "Expand conversation" }).click();
  await expect(pane).toHaveClass(/reading-agent/);
  await expect(input).toHaveValue("Preserve this draft");
  await pane.getByRole("button", { name: "Return conversation to canvas" }).click();
  await expect(pane).toHaveClass(/in-canvas/);
  await expect(input).toHaveValue("Preserve this draft");
  await pane.getByRole("button", { name: "Minimize agent" }).click();
  await expect(card).toBeFocused();
  await card.press("Enter");
  await openAgentConversation(page);
  await expect(input).toHaveValue("Preserve this draft");
  await page.reload();
  await expect(card).toBeVisible();
  const restored = (await card.boundingBox())!;
  expect(restored.x).toBeCloseTo(moved.x, 0);
  expect(restored.y).toBeCloseTo(moved.y, 0);
});

test("HUD locates off-screen work without losing the task and narrow conversations fit", async ({ page }) => {
  await page.setViewportSize({ width: 1200, height: 850 });
  await page.goto("/p/shop");
  const card = await prepareAgent(page);
  const id = await card.getAttribute("data-agent-id");
  // Browse is an intentional overlay above canvas bearings. Clear it before
  // exercising the left viewport edge, as a user would to reach that canvas area.
  await page.getByRole("button", { name: "Toggle navigation", exact: true }).click();
  const before = (await card.boundingBox())!;
  // Move this task beyond the viewport; the model and working context stay untouched.
  await page.mouse.move(before.x + 40, before.y + 20);
  await page.mouse.down();
  await page.mouse.move(5, 180, { steps: 8 });
  await page.mouse.up();
  await expect(page.getByRole("button", { name: "Locate New task", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Locate New task", exact: true }).click();
  await openAgentConversation(page);
  await expect(card).toHaveAttribute("data-agent-id", id!);
  await expect(card).toHaveAttribute("aria-pressed", "true");
  const pane = page.locator("#chat-pane");
  const located = (await pane.boundingBox())!;
  expect(located.x).toBeGreaterThan(12);
  expect(located.x + located.width).toBeLessThan(1200);
  await pane.getByLabel("Message the agent").fill("Keep while resizing");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator(".agent-hud-summary").click();
  await page.locator(`.agent-roster [data-agent-id="${id}"]`).click();
  await openAgentConversation(page);
  await expect(pane.getByLabel("Message the agent")).toHaveValue("Keep while resizing");
  const narrow = (await pane.boundingBox())!;
  expect(narrow.x).toBeGreaterThanOrEqual(0);
  expect(narrow.x + narrow.width).toBeLessThanOrEqual(390);
  expect(narrow.y + narrow.height).toBeLessThanOrEqual(844);
});

test("one task surface preserves the conversation draft through details", async ({ page }) => {
  await page.goto("/p/shop?item=order");
  const card = await prepareAgent(page);
  await card.click();
  await openAgentConversation(page);
  const pane = page.locator("#chat-pane");
  await expect(card).toBeHidden();
  await expect(pane.locator(".pane-title")).toHaveText("New task");
  await expect(pane.locator(".implementation-toolbar,.implementation-workspace")).toHaveCount(0);
  await expect(pane.getByRole("button", { name: "Reconnect" })).toHaveCount(0);
  await expect(pane.getByRole("button", { name: "Undo model edit" })).toHaveCount(0);
  await expect(pane.locator(".chat-composer").getByLabel("Editing scope")).toBeVisible();
  await expect(pane.locator(".chat-composer").getByLabel("Agent model")).toBeVisible();
  const input = pane.getByLabel("Message the agent");
  await input.fill("Retain my question");
  await pane.getByRole("button", { name: "Task details", exact: true }).click();
  const details = pane.getByRole("dialog", { name: "Task details", exact: true });
  await expect(details.getByText("Current checkout", { exact: true })).toBeVisible();
  await expect(details.getByRole("button", { name: "Discard task" })).toBeVisible();
  await details.getByRole("button", { name: "Close task details" }).press("Escape");
  await expect(details).toHaveCount(0);
  await expect(pane.getByRole("button", { name: "Task details", exact: true })).toBeFocused();
  await expect(input).toHaveValue("Retain my question");
  await pane.getByRole("button", { name: "Minimize agent" }).click();
  await expect(card).toBeVisible();
  await expect(card).not.toContainText("Project work");
  await card.press("Enter");
  await openAgentConversation(page);
  await expect(input).toHaveValue("Retain my question");
});
