import { locateAgent, openAgentConversation, prepareAgent } from "./fixtures/agent-ui";
import { test, expect } from "@playwright/test";
import { mkdtemp, mkdir, writeFile, readFile, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
test.use({ serviceWorkers: "block" });
const xml = '<lexicon schema="3.3" id="shop"><name>Shop</name><description>Orders.</description><context id="scope"><name>Ordering</name><description>Orders.</description><concept id="thing"><name>Order</name><description>A purchase.</description><code-link kind="code" file="order.ts" symbol="Order" role="representation">Stores the order.</code-link></concept></context><relationship id="owns" from="scope" to="thing"><name>owns</name><description>Owns orders.</description></relationship></lexicon>';

test("a task keeps its identity, approved model edits, context and composer draft while scope changes and other agents work", async ({ page, request }) => {
  const root = await mkdtemp(join(tmpdir(), "lexicon-unified-browser-"));
  try {
    await mkdir(join(root, "lexicon")); await writeFile(join(root, "lexicon/model.xml"), xml);
    await writeFile(join(root, "order.ts"), "export interface Order { id: string }");
    const project = await (await request.post("/api/projects", { data: { root } })).json();
    await page.goto(`/p/${project.id}?item=thing`);
    const first = await prepareAgent(page);
    await first.click();
    await openAgentConversation(page);
    const pane = page.locator('#chat-pane'), input = pane.getByRole('textbox', { name: 'Message the agent' });
    await expect(input).toBeFocused();
    await expect(pane.getByLabel('Editing scope')).toHaveValue('model');
    await expect(pane.getByLabel('Agent model')).toContainText('Test model');
    await expect(pane.getByLabel('Agent model')).not.toContainText('Claude');
    await input.fill('Rename Order to Purchase');
    await pane.getByRole('button', { name: 'Send', exact: true }).click();
    await expect(pane.getByText('Model delta staged · not saved', { exact: true })).toBeVisible();
    await expect(page.locator('main [data-reader-card].active h1')).toHaveText('Order');
    expect(await readFile(join(root, 'lexicon/model.xml'), 'utf8')).toBe(xml);
    await pane.getByRole('button', { name: 'Minimize agent', exact: true }).click();
    await page.getByRole('group', { name: 'Agent perspective', exact: true }).getByRole('button', { name: 'Approve changes', exact: true }).click();
    await expect(page.locator('main [data-reader-card].active h1')).toHaveText('Purchase');
    await openAgentConversation(page);
    await expect(first).toHaveAttribute('aria-label', /^Rename Order to Purchase:/);
    const agentId = await first.getAttribute('data-agent-id');
    let opening = 0;
    await page.route(`**/agent/open?agent=${agentId}`, async route => {
      expect(route.request().postDataJSON()).toEqual({});
      opening++;
      await route.fulfill(opening === 1 ? { json: { ok: true } } : { status: 400, json: { error: 'T3 Code does not know this environment.' } });
    });
    if (await pane.getByRole('button', { name: 'Task details', exact: true }).getAttribute('aria-expanded') !== 'true') await pane.getByRole('button', { name: 'Task details', exact: true }).click();
    await pane.getByRole('button', { name: 'Open in T3 Code' }).click();
    await expect.poll(() => opening).toBe(1);
    await expect(pane.getByText('Model delta staged · not saved', { exact: true })).toBeVisible();
    if (await pane.getByRole('button', { name: 'Task details', exact: true }).getAttribute('aria-expanded') !== 'true') await pane.getByRole('button', { name: 'Task details', exact: true }).click();
    await pane.getByRole('button', { name: 'Open in T3 Code' }).click();
    await expect(pane.getByRole('dialog', { name: 'Task details' }).getByRole('alert')).toContainText('does not know this environment');
    await pane.getByRole('button', { name: 'Close task details' }).click();
    await pane.getByLabel('Editing scope').selectOption('code');
    await expect(pane.getByLabel('Agent model')).not.toContainText('Claude');
    await input.fill('Keep this task draft');
    await page.locator('.new-agent-toggle').click();
    const menu = page.getByRole('dialog', { name: 'New agent' });
    await menu.getByPlaceholder('What is this agent working on?').fill('Review ordering');
    await expect(menu.getByText('Groomer', { exact: true })).toHaveCount(0);
    await menu.getByRole('button', { name: 'Start agent' }).click();
    await expect(input).toHaveValue('');
    await expect(pane.getByLabel('Editing scope')).toHaveValue('model');
    await input.fill('slow review');
    await pane.getByRole('button', { name: 'Send', exact: true }).click();
    await expect(pane.locator('.agent-heading-status')).toHaveText('Working');
    await locateAgent(page, 'Rename Order to Purchase');
    await expect(input).toHaveValue('Keep this task draft');
    await expect(pane.getByLabel('Editing scope')).toHaveValue('code');
    await expect(pane.getByText('Model delta staged · not saved', { exact: true })).toBeVisible();
    await expect(pane.getByRole('button', { name: /Undo/ })).toHaveCount(0);
    await expect(page.locator('main [data-reader-card].active h1')).toHaveText('Purchase');
    expect(await readFile(join(root, 'lexicon/model.xml'), 'utf8')).toContain('<name>Purchase</name>');
    await locateAgent(page, 'Review ordering');
    await pane.getByRole('button', { name: 'Stop', exact: true }).click();
    await expect(pane.getByRole('button', { name: 'Send', exact: true })).toBeVisible();
    await locateAgent(page, 'Rename Order to Purchase');
    await page.reload();
    await first.click();
    await openAgentConversation(page);
    await expect(pane.getByLabel('Editing scope')).toHaveValue('code');
    await expect(pane.getByText('Rename Order to Purchase', { exact: true }).last()).toBeVisible();
    await page.screenshot({ path: '/tmp/lexicon-unified-agent-desktop.png' });
    await page.setViewportSize({ width: 390, height: 844 });
    await locateAgent(page, 'Rename Order to Purchase');
    await expect(input).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: '/tmp/lexicon-unified-agent-mobile.png' });
  } finally { await page.goto('/').catch(() => {}); await rm(root, { recursive: true, force: true }); }
});

test("task sessions remain available when T3 is disconnected", async ({ page }) => {
  await page.route('**/api/settings', route => route.fulfill({ json: { revision: 1, connections: { t3: { configured: false, connected: false, url: 'http://127.0.0.1:5733', models: [] } } } }));
  await page.goto('/p/shop?item=order');
  await (await prepareAgent(page)).click();
  await openAgentConversation(page);
  const pane = page.locator('#chat-pane');
  await expect(pane.getByLabel('Pairing token')).toHaveCount(0);
  await page.getByRole('button', { name: 'Lexicon settings', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Lexicon settings' }).getByLabel('Pairing token')).toBeVisible();
  await page.getByRole('button', { name: 'Done', exact: true }).click();
  await pane.getByLabel('Message the agent').fill('Explain this rule');
  await expect(pane.getByRole('button', { name: 'Send', exact: true })).toBeDisabled();
  await expect(pane.getByLabel('Editing scope')).toHaveValue('model');
  await page.locator('.new-agent-toggle').click();
  await page.getByRole('dialog', { name: 'New agent' }).getByRole('button', { name: 'Start agent' }).click();
  await expect(page.locator('.agent-session-button')).toHaveCount(2);
});
