import { expect, test } from "@playwright/test";

test("drawing tray docks centrally, keeps tools functional, and falls back without resizing canvas", async ({ page }) => {
  await page.goto("/p/shop?item=order");
  const dock = page.locator(".canvas-docked-tools");
  await expect(dock).toBeVisible();
  const toolbar = page.locator(".canvas-top > .toolbar");
  const bar = (await toolbar.boundingBox())!;
  const tray = (await dock.locator(".tlui-main-toolbar__tools").boundingBox())!;
  expect(Math.abs(tray.x + tray.width / 2 - bar.x - bar.width / 2)).toBeLessThan(2);
  expect(tray.y).toBeGreaterThanOrEqual(bar.y);
  expect(tray.y + tray.height).toBeLessThanOrEqual(bar.y + bar.height);
  const canvas = await page.locator(".canvas-stage").boundingBox();
  await dock.getByTestId("tools.draw").click();
  await expect(dock.getByTestId("tools.draw")).toHaveAttribute("aria-pressed", "true");
  await page.keyboard.press("v");
  await expect(dock.getByTestId("tools.select")).toHaveAttribute("aria-pressed", "true");
  await dock.getByTestId("tools.more-button").click();
  await page.getByTestId("tools.more.ellipse").click();
  await expect(dock.getByTestId("tools.ellipse").filter({ visible: true })).toHaveAttribute("aria-pressed", "true");
  const lock = dock.getByTestId("tool-lock");
  await expect(lock).toBeVisible();
  const lockBox = (await lock.boundingBox())!;
  const lockedTray = (await dock.locator(".tlui-main-toolbar__tools").boundingBox())!;
  expect(lockedTray.y).toBe(tray.y);
  expect(lockBox.y).toBeGreaterThanOrEqual(bar.y);
  expect(lockBox.y + lockBox.height).toBeLessThanOrEqual(bar.y + bar.height);
  expect(lockBox.x).toBeGreaterThanOrEqual(lockedTray.x + lockedTray.width);
  const unlockedIcon = (await lock.locator(".tlui-icon").getAttribute("style"))!;
  await lock.click();
  await expect(lock.locator(".tlui-icon")).not.toHaveAttribute("style", unlockedIcon);
  await lock.click();
  await expect(lock.locator(".tlui-icon")).toHaveAttribute("style", unlockedIcon);
  await page.getByRole("button", { name: "Toggle reader", exact: true }).click();
  expect(await page.locator(".canvas-stage").boundingBox()).toEqual(canvas);
  await expect(dock).toBeVisible();
  await page.getByRole("button", { name: "Use dark theme", exact: true }).click();
  await expect(dock).toHaveClass(/tl-theme__dark/);
  await page.screenshot({ path: "test-results/toolbar-dock-dark.png" });
  await page.setViewportSize({ width: 1100, height: 1000 });
  await expect(dock).toHaveCount(0);
  await expect(page.locator(".canvas-stage .tlui-main-toolbar")).toBeVisible();
  await expect(page.getByTestId("tools.ellipse").filter({ visible: true })).toHaveAttribute("aria-pressed", "true");
  await page.setViewportSize({ width: 1600, height: 1000 });
  await expect(dock).toBeVisible();
  await expect(dock.getByTestId("tools.ellipse").filter({ visible: true })).toHaveAttribute("aria-pressed", "true");
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(dock).toHaveCount(0);
  await expect(page.locator(".canvas-stage .tlui-main-toolbar")).toBeVisible();
});
